## Chapter 14 Simipfying data with the singular value decomposition: Machine Learnin in Action

In [2]:
from numpy import *
from numpy import linalg as la

def loadExData():
    return[[0, 0, 0, 2, 2],
          [0, 0, 0, 3, 3],
          [0, 0, 0, 1, 1],
          [1, 1, 1, 0, 0],
          [2, 2, 2, 0, 0],
          [5, 5, 5, 0, 0],
          [1, 1, 1, 0, 0]]

In [3]:
Data = loadExData()

In [4]:
U,Sigma,VT = linalg.svd(Data) 

In [5]:
Sigma

array([9.64365076e+00, 5.29150262e+00, 8.10743804e-16, 8.49555901e-17,
       7.85046229e-17])

In [6]:
U

array([[ 1.24153973e-16, -5.34522484e-01,  8.37807144e-01,
        -6.21797365e-02, -6.15166652e-02,  6.14119433e-02,
         3.07059717e-02],
       [ 1.38448957e-32, -8.01783726e-01, -4.85697270e-01,
         3.48196811e-01, -1.70447338e-17,  5.55111512e-17,
         2.77555756e-17],
       [ 0.00000000e+00, -2.67261242e-01, -2.18522479e-01,
        -9.20230960e-01,  1.23033330e-01, -1.22823887e-01,
        -6.14119433e-02],
       [-1.79605302e-01, -2.05774198e-17, -4.40327302e-02,
        -6.14209440e-02, -9.19287207e-01, -3.05864745e-01,
        -1.52932373e-01],
       [-3.59210604e-01,  2.46872204e-17, -8.80654604e-02,
        -1.22841888e-01, -2.06818517e-01,  8.95901251e-01,
        -5.20493747e-02],
       [-8.98026510e-01, -2.34936928e-17,  5.28392762e-02,
         7.37051328e-02,  2.87266700e-01, -2.86777676e-01,
        -1.43388838e-01],
       [-1.79605302e-01,  1.23436102e-17, -4.40327302e-02,
        -6.14209440e-02, -1.03409259e-01, -5.20493747e-02,
         9.7397531

In [7]:
VT

array([[-5.77350269e-01, -5.77350269e-01, -5.77350269e-01,
         0.00000000e+00,  0.00000000e+00],
       [-2.46566547e-16,  1.23283273e-16,  1.23283273e-16,
        -7.07106781e-01, -7.07106781e-01],
       [ 7.23982597e-01, -6.88926918e-01, -3.50556793e-02,
        -3.33066907e-16, -2.77555756e-16],
       [-3.77512736e-01, -4.38230953e-01,  8.15743689e-01,
        -1.11022302e-16,  0.00000000e+00],
       [-0.00000000e+00, -7.85046229e-17,  7.85046229e-17,
         7.07106781e-01, -7.07106781e-01]])

In [8]:
Sig3 = mat([[Sigma[0], 0, 0], [0, Sigma[1], 0], [0, 0, Sigma[2]]])

In [9]:
U[:, :3]*Sig3*VT[:3,:]

matrix([[ 4.97898416e-16, -1.50790933e-15, -1.06376928e-15,
          2.00000000e+00,  2.00000000e+00],
        [ 7.61006254e-16, -2.51763710e-16, -5.09242545e-16,
          3.00000000e+00,  3.00000000e+00],
        [ 2.20432837e-16, -5.22946258e-17, -1.68138212e-16,
          1.00000000e+00,  1.00000000e+00],
        [ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
          7.69936548e-17,  7.69936548e-17],
        [ 2.00000000e+00,  2.00000000e+00,  2.00000000e+00,
         -9.23711205e-17, -9.23711205e-17],
        [ 5.00000000e+00,  5.00000000e+00,  5.00000000e+00,
          8.79053493e-17,  8.79053493e-17],
        [ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         -4.61855603e-17, -4.61855603e-17]])

In [45]:
def ecludSim(inA,inB):
    return 1.0/(1.0 + la.norm(inA - inB))

def pearsSim(inA,inB):
    if len(inA) < 3 : return 1.0
    return 0.5+0.5*corrcoef(inA, inB, rowvar = 0)[0][1]

def cosSim(inA,inB):
    num = float(inA.T*inB)
    denom = la.norm(inA)*la.norm(inB)
    return 0.5+0.5*(num/denom)

In [46]:
myMat = mat(loadExData())

In [47]:
ecludSim(myMat[:,0],myMat[:,4])

0.12973190755680383

In [48]:
ecludSim(myMat[:,0],myMat[:,0])

1.0

In [49]:
cosSim(myMat[:, 0], myMat[:,4])

0.5

In [50]:
cosSim(myMat[:,0], myMat[:,0])

1.0

In [54]:
pearsSim(myMat[:,0],myMat[:,4])

0.20596538173840329

In [55]:
pearsSim(myMat[:,0],myMat[:,0])

1.0

In [83]:
def standEst(dataMat, user, simMeas, item):
    n = shape(dataMat)[1]
    simTotal = 0.0; ratSimTotal = 0.0
    for j in range(n):
        userRating = dataMat[user,j]
        if userRating == 0: continue
        overLap = nonzero(logical_and(dataMat[:,item].A>0, \
                                      dataMat[:,j].A>0))[0]
        if len(overLap) == 0: similarity = 0
        else: similarity = simMeas(dataMat[overLap,item], \
                                   dataMat[overLap,j])
        #print('the %d and %d similarity is: %f' % (item, j, similarity))
        simTotal += similarity
        ratSimTotal += similarity * userRating
    if simTotal == 0: return 0
    else: return ratSimTotal/simTotal

def recommend(dataMat, user, N=3, simMeas=cosSim, estMethod=standEst):
    unratedItems = nonzero(dataMat[user,:].A==0)[1]#find unrated items 
    if len(unratedItems) == 0: return 'you rated everything'
    itemScores = []
    for item in unratedItems:
        estimatedScore = estMethod(dataMat, user, simMeas, item)
        itemScores.append((item, estimatedScore))
    return sorted(itemScores, key=lambda jj: jj[1], reverse=True)[:N]

In [84]:
myMat = mat(loadExData())

In [85]:
myMat[0,1] = myMat[0,0] = myMat[1, 0] = myMat[2, 0] = 4

In [86]:
myMat[3, 3] = 2

In [87]:
myMat

matrix([[4, 4, 0, 2, 2],
        [4, 0, 0, 3, 3],
        [4, 0, 0, 1, 1],
        [1, 1, 1, 2, 0],
        [2, 2, 2, 0, 0],
        [5, 5, 5, 0, 0],
        [1, 1, 1, 0, 0]])

In [88]:
recommend(myMat, 2)

[(2, 2.5), (1, 2.0243290220056256)]

In [89]:
recommend(myMat, 2, simMeas=ecludSim)

[(2, 3.0), (1, 2.8266504712098603)]

In [90]:
recommend(myMat, 2, simMeas=pearsSim)

[(2, 2.5), (1, 2.0)]

In [91]:
def loadExData2():
    return[[0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 5],
           [0, 0, 0, 3, 0, 4, 0, 0, 0, 0, 3],
           [0, 0, 0, 0, 4, 0, 0, 1, 0, 4, 0],
           [3, 3, 4, 0, 0, 0, 0, 2, 2, 0, 0],
           [5, 4, 5, 0, 0, 0, 0, 5, 5, 0, 0],
           [0, 0, 0, 0, 5, 0, 1, 0, 0, 5, 0],
           [4, 3, 4, 0, 0, 0, 0, 5, 5, 0, 1],
           [0, 0, 0, 4, 0, 4, 0, 0, 0, 0, 4],
           [0, 0, 0, 2, 0, 2, 5, 0, 0, 1, 2],
           [0, 0, 0, 0, 5, 0, 0, 0, 0, 4, 0],
           [1, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0]]

In [92]:
U,Sigma,VT = la.svd(mat(loadExData2()))

In [93]:
U

matrix([[-0.02173672, -0.41043862, -0.29555566, -0.31993924,  0.77606298,
          0.15828951, -0.0435284 ,  0.02059981, -0.02594897,  0.10460968,
          0.00940588],
        [-0.01664767, -0.40868796, -0.29149768, -0.15138979, -0.33933823,
         -0.02422168, -0.14675961,  0.578175  ,  0.19363235, -0.46295592,
         -0.03773245],
        [-0.03763173, -0.27302481,  0.4269746 , -0.10978297, -0.0155641 ,
         -0.1131373 ,  0.57177959,  0.33872886, -0.13586013,  0.17290962,
          0.4760405 ],
        [-0.3928286 ,  0.03215633,  0.00283676,  0.02145489, -0.11989979,
          0.7023584 , -0.17084214, -0.12090699, -0.21988993, -0.19766208,
          0.45307019],
        [-0.68146521,  0.05125169,  0.00962441,  0.02067521, -0.06539204,
          0.02800613, -0.09643557,  0.34249592,  0.09728232,  0.53792639,
         -0.31932109],
        [-0.01031581, -0.35826614,  0.52908411,  0.06256753,  0.03236161,
          0.05503535, -0.18939118, -0.01918345, -0.5197144 , -0.2053250

In [94]:
Sigma

array([15.77075346, 11.40670395, 11.03044558,  4.84639758,  3.09292055,
        2.58097379,  1.00413543,  0.72817072,  0.43800353,  0.22082113,
        0.07367823])

In [95]:
Sig2 = Sigma**2

In [96]:
sum(Sig2)

541.9999999999995

In [97]:
sum(Sig2)*0.9

487.7999999999996

In [98]:
sum(Sig2[:2])

378.8295595113579

In [99]:
sum(Sig2[:3])

500.50028912757926

In [111]:
def svdEst(dataMat, user, simMeas, item):
    n = shape(dataMat)[1]
    simTotal = 0.0; ratSimTotal = 0.0
    U,Sigma,VT = la.svd(dataMat)
    Sig4 = mat(eye(4)*Sigma[:4]) #arrange Sig4 into a diagonal matrix
    xformedItems = dataMat.T * U[:,:4] * Sig4.I  #create transformed items
    for j in range(n):
        userRating = dataMat[user,j]
        if userRating == 0 or j==item: continue
        similarity = simMeas(xformedItems[item,:].T,\
                             xformedItems[j,:].T)
        print('the %d and %d similarity is: %f' % (item, j, similarity))
        simTotal += similarity
        ratSimTotal += similarity * userRating
    if simTotal == 0: return 0
    else: return ratSimTotal/simTotal

In [112]:
recommend(myMat, 1, estMethod=svdEst)

the 1 and 0 similarity is: 0.498142
the 1 and 3 similarity is: 0.498131
the 1 and 4 similarity is: 0.509974
the 2 and 0 similarity is: 0.552670
the 2 and 3 similarity is: 0.552976
the 2 and 4 similarity is: 0.217301


[(2, 3.4177569186592383), (1, 3.3307171545585637)]

In [114]:
recommend(myMat, 1, estMethod=svdEst)

the 1 and 0 similarity is: 0.498142
the 1 and 3 similarity is: 0.498131
the 1 and 4 similarity is: 0.509974
the 2 and 0 similarity is: 0.552670
the 2 and 3 similarity is: 0.552976
the 2 and 4 similarity is: 0.217301


[(2, 3.4177569186592383), (1, 3.3307171545585637)]

### Image-Compression function

In [128]:
def printMat(inMat, thresh=0.8):
    for i in range(32):
        for k in range(32):
            if float(inMat[i,k]) > thresh:
                print(1)
            else: print(0)
        print('') 

def imgCompress(numSV=3, thresh=0.8):
    myl = []
    for line in open('0_5.txt').readlines():
        newRow = []
        for i in range(32):
            newRow.append(int(line[i]))
        myl.append(newRow)
    myMat = mat(myl)
    print("****original matrix******")
    printMat(myMat, thresh)
    U,Sigma,VT = la.svd(myMat)
    SigRecon = mat(zeros((numSV, numSV)))
    for k in range(numSV):#construct diagonal matrix from vector
        SigRecon[k,k] = Sigma[k]
    reconMat = U[:,:numSV]*SigRecon*VT[:numSV,:]
    print("****reconstructed matrix using %d singular values******" % numSV)
    printMat(reconMat, thresh)

In [129]:
imgCompress(2)

****original matrix******
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0

0
0
0
0
0
0
0
0
0
0
0
0
1
1
1
1
1
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0

0
0
0
0
0
0
0
0
0
0
0
1
1
1
1
1
1
1
1
0
0
0
0
0
0
0
0
0
0
0
0
0

0
0
0
0
0
0
0
0
0
0
1
1
1
1
1
1
1
1
1
1
0
0
0
0
0
0
0
0
0
0
0
0

0
0
0
0
0
0
0
0
1
1
1
1
1
1
1
1
1
1
1
1
1
0
0
0
0
0
0
0
0
0
0
0

0
0
0
0
0
0
0
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
0
0
0
0
0
0
0
0
0
0

0
0
0
0
0
0
0
0
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
0
0
0
0
0
0
0
0
0

0
0
0
0
0
0
0
0
1
1
1
1
1
1
1
0
0
0
0
1
1
1
1
1
0
0
0
0
0
0
0
0

0
0
0
0
0
0
0
1
1
1
1
1
1
1
0
0
0
0
0
1
1
1
1
1
0
0
0
0
0
0
0
0

0
0
0
0
0
0
1
1
1
1
1
1
0
0
0
0
0
0
0
0
1
1
1
1
0
0
0
0
0
0
0
0

0
0
0
0
0
0
1
1
1
1
1
1
0
0
0
0
0
0
0
0
1
1
1
1
1
0
0
0
0
0
0
0

0
0
0
0
0
0
1
1
1
1
1
1
0
0
0
0
0
0
0
0
0
1
1
1
1
0
0
0
0
0
0
0

0
0
0
0
0
0
1
1
1
1
1
1
0
0
0
0
0
0
0
0
0
1
1
1
1
0
0
0
0
0
0
0

0
0
0
0
0
0
0
1
1
1
1
1
1
0
0
0
0
0
0
0
0
0
1
1
1
1
0
0
0
0
0
0

0
0
0
0
0
0
1
1
1
1
1
1
1
0
0
0
0
0
0
0
0
0
1
1
1
1
0
0
0
0
0
0
